// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams} from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
    | 'de'
    | 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {}

export type TranslationFunctions = {
    "chess:q": string,
    "chess:k": string,
    "chess:r": string,
    "chess:b": string,
    "chess:n": string,
    "chess:Q": string,
    "chess:K": string,
    "chess:R": string,
    "chess:B": string,
    "chess:N": string,
    "buttons:flipper": string,
    "buttons:first": string,
    "buttons:prev": string,
    "buttons:next": string,
    "buttons:play": string,
    "buttons:last": string,
    "buttons:deleteVar": string,
    "buttons:promoteVar": string,
    "buttons:deleteMoves": string,
    "buttons:nags": string,
    "buttons:pgn": string,
    "buttons:hidePGN": string,
}

export type Formatters = {}
