examples = {};

examples["1000"] = {
    desc: "Use PgnViewerJS for only displaying a board. See the section \"Boards\" for details on that.",
    html: "<div id=\"board\" style=\"width: 400px\"><\/div>",
    name: "Board with defaults",
    jsStr: "var board = pgnBoard('board', {});",
    jsFn: function() {
        var board = pgnBoard('board', {});
    }
};

examples["1001"] = {
    desc: "Use PgnViewerJS for showing a (short) game. The buttons, the board and the display of the " +
        "moves are all default values, that may be changed by configuration parameters. Parameter pgn is " +
        "mandatory when using \"pgnView\".",
    html: "<div id=\"board\" style=\"width: 400px\"><\/div>",
    name: "Shortest game possible",
    jsStr: "var pgn = \"1. f4 e6 2. g4 Qh4#\";\nvar board = pgnView('board', {pgn: pgn});",
    jsFn: function() {
        var pgn = "1. f4 e6 2. g4 Qh4#";
        var board = pgnView('board', {pgn: pgn});
    }
};

examples["1002"] = {
    desc: "Use PgnViewerJS for displaying a game in typical notation, with diagrams and different styles " +
        "for the moves, the boards, ... Looks similar to the style of some magazines or books. " +
        "For the diagram, I have taken the NAG 'D' (or $220), see <a href=\"http://en.wikipedia.org/wiki/Numeric_Annotation_Glyphs\">NAGs at Wikipedia</a> for details",
    html: "<div id=\"board\" style=\"width: 250px\"><\/div>",
    name: "Printing a game",
    jsStr: "var pgn = \"1. f4 e6 2. g4D Qh4#$220\";\nvar board = pgnPrint('board', {pgn: pgn});",
    jsFn: function() {
        var pgn = "1. f4 e6 2. g4D { what a horrible move (but the shortest mate " +
            "you can get ...) } Qh4#$220";
        var board = pgnPrint('board', {pgn: pgn});
    }
};

examples["1003"] = {
    desc: "Use PgnViewerJS for viewing a game with the option to edit it by adding variations, comments, ..." +
        "So start playing on the board, take moves back, and test variations. Not all " +
        "buttons are implemented, but the PGN button works and displays the current " +
        "game in the pgn notation (including comments).",
    html: "<div id=\"board\" style=\"width: 300px\"><\/div>",
    name: "Editing a game",
    jsStr: "var board = pgnEdit('board', {});",
    jsFn: function() {
        var board = pgnEdit('board', {});
    }
};

examples["1020"] = {
    desc: "ChessBoard initializes to the starting position on board with an empty configuration.",
    html: "<div id=\"board\" style=\"width: 400px\"><\/div>",
    name: "Starting Board",
    jsStr: "var board = pgnBoard('board', {});",
    jsFn: function() {
        var board = pgnBoard('board', {});
    }
};
examples["1021"] = {
    desc: "ChessBoard pieceStyle 'merida', 'case', 'wikipedia', 'alpha', 'uscf', 'condal', 'maya', and 'leipzig'.",
    html: 'Merida <div id="board"></div> Case <div id="board2"></div> Wikipedia <div id="board3"></div> Alpha <div id="board4"></div>' + 
    ' USCF <div id="board5"></div>  Condal <div id="board7"></div> Maya <div id="board8"></div> Leipzig <div id="board9"></div>',
    name: "Piece Styles",
    jsStr: "var board = pgnBoard('board', {pieceStyle: 'merida', boardSize: '400px'});\nvar board2 = pgnBoard('board2', {pieceStyle: 'case', boardSize: '400px'});\nvar board3 = pgnBoard('board3', {pieceStyle: 'wikipedia', boardSize: '400px'});\nvar board4 = pgnBoard('board4', {pieceStyle: 'alpha',  boardSize: '400px'});\nvar board5 = pgnBoard('board5', {pieceStyle: 'uscf',  boardSize: '400px'});\nvar board7 = pgnBoard('board7', {pieceStyle: 'condal', boardSize: '400px'});\nvar board8 = pgnBoard('board8', {pieceStyle: 'maya',  boardSize: '400px'});\nvar board9 = pgnBoard('board9', {pieceStyle: 'leipzig', boardSize: '400px'});",
    jsFn: function() {
        var board = pgnBoard('board', {pieceStyle: 'merida', boardSize: '400px'});
        var board2 = pgnBoard('board2', {pieceStyle: 'case', boardSize: '400px'});
        var board3 = pgnBoard('board3', {pieceStyle: 'wikipedia', boardSize: '400px'});
        var board4 = pgnBoard('board4', {pieceStyle: 'alpha',  boardSize: '400px'});
        var board5 = pgnBoard('board5', {pieceStyle: 'uscf',  boardSize: '400px'});
        var board7 = pgnBoard('board7', {pieceStyle: 'condal', boardSize: '400px'});
        var board8 = pgnBoard('board8', {pieceStyle: 'maya',  boardSize: '400px'});
        var board9 = pgnBoard('board9', {pieceStyle: 'leipzig', boardSize: '400px'});
    }
};

examples["1022"] = {
    desc: "ChessBoard with different positions. See the start position, a short finished game " +
        "and the Ruy Lopez after the first three moves. The positions are given as " +
        "FEN strings (see <a href=\"http://en.wikipedia.org/wiki/Forsyth–Edwards_Notation\">Forsyth–Edwards Notation</a> for details to that)." +
        "FEN strings are normally generated by software like ChessBase or Scid.",
    html: "<div id=\"b1\" style=\"width: 300px; margin: 20px\"><\/div>\n<div id=\"b2\" style=\"width: 300px; margin: 20px\"><\/div>" +
        "\n<div id=\"b3\" style=\"width: 300px; margin: 20px\"><\/div>",
    name: "Different positions",
    jsStr: "var fen1 = 'start';" +
        "\nvar fen2 = 'rnb1kbnr/pppp1ppp/4p3/8/5PPq/8/' +" +
        "\n     'PPPPP2P/RNBQKBNR w KQkq - 0 3';" +
        "\nvar fen3 = 'r1bqkbnr/1ppp1ppp/p1n5/1B2p3/4P3/5N2/' +" +
        "\n     'PPPP1PPP/RNBQK2R w KQkq - 0 4';" +
        "\npgnBoard('b1', {fen: fen1});" +
        "\npgnBoard('b2', {position: fen2});" +
        "\npgnBoard('b3', {position: fen3});",
    jsFn: function() {
        var fen1 = 'start';
        var fen2 = 'rnb1kbnr/pppp1ppp/4p3/8/5PPq/8/PPPPP2P/RNBQKBNR w KQkq - 0 3';
        var fen3 = 'r1bqkbnr/1ppp1ppp/p1n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 4';
        pgnBoard('b1', {position: fen1});
        pgnBoard('b2', {position: fen2});
        pgnBoard('b3', {position: fen3});
    }
};

examples["1023"] = {
    desc: "ChessBoard with different additional configuration parameters. Used are here orientation and showNotation.",
    html: "<div id=\"b1\" style=\"width: 300px; margin: 20px\"><\/div>" +
        "\n<div id=\"b2\" style=\"width: 300px; margin: 20px\"><\/div>",
    name: "Additional parameters",
    jsStr: "pgnBoard('b1', {orientation: 'black'});" +
        "\npgnBoard('b2', {showNotation: false});",
    jsFn: function() {
        pgnBoard('b1', {orientation: 'black'});
        pgnBoard('b2', {showNotation: false});
    }
};

examples["1024"] = {
    desc: "ChessBoard with different board sizes.",
    html: "<div id='b1'></div><br/>" +
        "\n<div id='b2'></div><br/>" +
        "\n<div id='b3'></div>",
    name: "Different board sizes  set in the configuration",
    jsStr: "pgnBoard('b1', {boardSize: '200px'});" +
        "\npgnBoard('b2', {boardSize: '350px'});" +
        "\npgnBoard('b3', {boardSize: '500px'});",
    jsFn: function() {
        pgnBoard('b1', {boardSize: '200px'});
        pgnBoard('b2', {boardSize: '350px'});
        pgnBoard('b3', {boardSize: '500px'});
    }
};

examples["1050"] = {
    desc: "This is the same theme again, with a typical example to show how the game is displayed. Have a look at the headers, board and the moves.",
    html: "<div id=\"b1\" style=\"width: 390px\"><\/div>",
    name: "Complete game in Chess.com style",
    jsStr: "pgn = '[White \"Anderssen, Adolf\"][Black \"Dufresne, Jean\"] 1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1 Qxf3 20.Rxe7+ Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0';" +
        "\npgnView('b1', {pgn: pgn, theme: 'chesscom', boardSize: '200px',  movesWidth: '180px', scrollable: true, movesHeight: '220px'});",
    jsFn: function() {
        pgn = '[White "Anderssen, Adolf"][Black "Dufresne, Jean"]' +
            ' 1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1 Qxf3 20.Rxe7+ Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0';
        pgnView('b1', {pgn: pgn, theme: 'chesscom', boardSize: '200px', movesWidth: '180px', scrollable: true, movesHeight: "220px"});
    }
};
examples["1051"] = {
    desc: "An example for a normal game, with the standard style. Try to use the buttons, and play the game forth and back. You may set any position in the game by just clicking on the move.",
    html: "<div id=\"b1\" style=\"width: 380px\"><\/div>",
    name: "Normal Game",
    jsStr: "var pgn = '[White \"Anderssen, Adolf\"][Black \"Dufresne, Jean\"][Result \"1-0\"][ECO \"C52\"][Site \"Berlin\"][Date \"1852\"] 1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0';\n pgnv = pgnView('b1', {pgn: pgn});",
    jsFn: function() {
        var pgn = ['[White "Anderssen, Adolf"][Black "Dufresne, Jean"]',
            '[Result "1-0"][ECO "C52"]',
            '[Site "Berlin"][Date "1852"]',
            '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0'].join(" ");
        pgnv = pgnView("b1", {pgn: pgn});
    }
};
examples["1052"] = {
    desc: "The same game in a more traditional style",
    html: "<div id=\"b1\" style=\"width: 380px\"><\/div>",
    name: "Falken Style",
    jsStr: "var pgn = ['[White \"Anderssen, Adolf\"][Black \"Dufresne, Jean\"]', \n '[Result \"1-0\"][ECO \"C52\"]', \n '[Site \"Berlin\"][Date \"1852\"]',\n '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0']\n.join(\" \");\npgnv = pgnView('b1', {pgn: pgn, theme: 'falken'});",
    jsFn: function() {
        var pgn = ['[White "Anderssen, Adolf"][Black "Dufresne, Jean"]',
            '[Result "1-0"][ECO "C52"]',
            '[Site "Berlin"][Date "1852"]',
            '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0'].join(" ");
        pgnv = pgnView("b1", {pgn: pgn, theme: 'falken'});
    }
};
examples["1053"] = {
    desc: "The same game in green style",
    html: "<div id=\"b1\" style=\"width: 360px\"><\/div>",
    name: "Green Style",
    jsStr: "var pgn = ['[White \"Anderssen, Adolf\"][Black \"Dufresne, Jean\"]', \n '[Result \"1-0\"][ECO \"C52\"]', \n '[Site \"Berlin\"][Date \"1852\"]',\n '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0']\n.join(\" \");\npgnv = pgnView('b1', {pgn: pgn, theme: 'green'});",
    jsFn: function() {
        var pgn = ['[White "Anderssen, Adolf"][Black "Dufresne, Jean"]',
            '[Result "1-0"][ECO "C52"]',
            '[Site "Berlin"][Date "1852"]',
            '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0'].join(" ");
        pgnv = pgnView("b1", {pgn: pgn, theme: 'green'});
    }
};
examples["1054"] = {
    desc: "The same game in Zeit style",
    html: "<div id=\"b1\" style=\"width: 360px\"><\/div>",
    name: "Zeit Style",
    jsStr: "var pgn = ['[White \"Anderssen, Adolf\"][Black \"Dufresne, Jean\"]', \n '[Result \"1-0\"][ECO \"C52\"]', \n '[Site \"Berlin\"][Date \"1852\"]',\n '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0']\n.join(\" \");\npgnv = pgnView('b1', {pgn: pgn, theme: 'zeit'});",
    jsFn: function() {
        var pgn = ['[White "Anderssen, Adolf"][Black "Dufresne, Jean"]',
            '[Result "1-0"][ECO "C52"]',
            '[Site "Berlin"][Date "1852"]',
            '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0'].join(" ");
        pgnv = pgnView("b1", {pgn: pgn, theme: 'zeit'});
    }
};
examples["1055"] = {
    desc: "The same game in informator style",
    html: "<div id=\"b1\" style=\"width: 360px\"><\/div>",
    name: "Informator Style",
    jsStr: "var pgn = ['[White \"Anderssen, Adolf\"][Black \"Dufresne, Jean\"]', \n '[Result \"1-0\"][ECO \"C52\"]', \n '[Site \"Berlin\"][Date \"1852\"]',\n '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0']\n.join(\" \");\npgnv = pgnView('b1', {pgn: pgn, theme: 'informator'});",
    jsFn: function() {
        var pgn = ['[White "Anderssen, Adolf"][Black "Dufresne, Jean"]',
            '[Result "1-0"][ECO "C52"]',
            '[Site "Berlin"][Date "1852"]',
            '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0'].join(" ");
        pgnv = pgnView("b1", {pgn: pgn, theme: 'informator'});
    }
};
examples["1056"] = {
    desc: "The same game in sportverlag style",
    html: "<div id=\"b1\" style=\"width: 360px\"><\/div>",
    name: "Sportverlag Style",
    jsStr: "var pgn = ['[White \"Anderssen, Adolf\"][Black \"Dufresne, Jean\"]', \n '[Result \"1-0\"][ECO \"C52\"]', \n '[Site \"Berlin\"][Date \"1852\"]',\n '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0']\n.join(\" \");\npgnv = pgnView('b1', {pgn: pgn, theme: 'sportverlag'});",
    jsFn: function() {
        var pgn = ['[White "Anderssen, Adolf"][Black "Dufresne, Jean"]',
            '[Result "1-0"][ECO "C52"]',
            '[Site "Berlin"][Date "1852"]',
            '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0'].join(" ");
        pgnv = pgnView("b1", {pgn: pgn, theme: 'sportverlag'});
    }
};
examples["1057"] = {
    desc: "The same game in beyer style",
    html: "<div id=\"b1\" style=\"width: 360px\"><\/div>",
    name: "Beyer Style",
    jsStr: "var pgn = ['[White \"Anderssen, Adolf\"][Black \"Dufresne, Jean\"]', \n '[Result \"1-0\"][ECO \"C52\"]', \n '[Site \"Berlin\"][Date \"1852\"]',\n '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0']\n.join(\" \");\npgnv = pgnView('b1', {pgn: pgn, theme: 'beyer'});",
    jsFn: function() {
        var pgn = ['[White "Anderssen, Adolf"][Black "Dufresne, Jean"]',
            '[Result "1-0"][ECO "C52"]',
            '[Site "Berlin"][Date "1852"]',
            '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0'].join(" ");
        pgnv = pgnView("b1", {pgn: pgn, theme: 'beyer'});
    }
};
examples["1058"] = {
    desc: "The same game in a blue style",
    html: "<div id=\"b1\" style=\"width: 360px\"><\/div>",
    name: "Blue Style",
    jsStr: "var pgn = ['[White \"Anderssen, Adolf\"][Black \"Dufresne, Jean\"]', \n '[Result \"1-0\"][ECO \"C52\"]', \n '[Site \"Berlin\"][Date \"1852\"]',\n '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0']\n.join(\" \");\npgnv = pgnView('b1', {pgn: pgn, theme: 'blue'});",
    jsFn: function() {
        var pgn = ['[White "Anderssen, Adolf"][Black "Dufresne, Jean"]',
            '[Result "1-0"][ECO "C52"]',
            '[Site "Berlin"][Date "1852"]',
            '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0'].join(" ");
        pgnv = pgnView("b1", {pgn: pgn, theme: 'blue'});
    }
};
examples["1100"] = {
    desc: "This is an example of a chess game, where the moves are not only shown, but can be " +
        "changed. Try to play on the board, use the move, before and after comments, switch " +
        "between them. Insert new moves, and see the display changing. " +
        "Try to find the PGN button, and refresh the display when you have changed " +
        "a comment.",
    html: "<div id=\"b1\" style=\"width: 360px\"><\/div>",
    name: "Edit game",
    jsStr: "var pgn = ['[White \"Anderssen, Adolf\"][Black \"Dufresne, Jean\"]', \n '[Result \"1-0\"][ECO \"C52\"]', \n '[Site \"Berlin\"][Date \"1852\"]',\n '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0']\n.join(\" \");\npgnv = pgnEdit('b1', {pgn: pgn});",
    jsFn: function() {
        var pgn = ['[White "Anderssen, Adolf"][Black "Dufresne, Jean"]',
            '[Result "1-0"][ECO "C52"]',
            '[Site "Berlin"][Date "1852"]',
            '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1!  Qxf3? 20.Rxe7+! Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0'].join(" ");
        pgnv = pgnEdit("b1", {pgn: pgn});
    }
};
examples["1101"] = {
    desc: "Here the normal layout of the moves, with some special characters, the so called NAGs. PNGViewerJS knows the NAGs, and " +
        "translates them in the correct notation. The following game " +
        "is not really correct commented, but it shows the different options.\nNot all characters are available in all fonts, so we should " +
        "check that ....",
    html: "<div id=\"b1\" style=\"width: 360px\"><\/div>",
    name: "Annotated moves",
    jsStr: "var pgn = '1. e4$1 e5$2 2. Nf3$3 Nc6$4 3. Bb5$5 a6$6 4. Ba4$7 Nf6$10 5. O-O$13 Be7$14 6. Re1$15 b5$16 7. Bb3$17 O-O$18 8. c3$19 d5$3';\npgnView('b1', {pgn: pgn});",
    jsFn: function() {
        var pgn = '1. e4$1 e5$2 2. Nf3$3 Nc6$4 3. Bb5$5 a6$6 4. Ba4$7 Nf6$10 5. O-O$13 Be7$14 6. Re1$15 b5$16 7. Bb3$17 O-O$18 8. c3$19 d5$3';
        pgnView('b1', {pgn: pgn});
    }
};
examples["1102"] = {
    desc: "Here a game with a lot of variations, sometimes two or more levels deep. This is part of my opening repertoire as white.",
    html: "<div id=\"b1\" style=\"width: 360px\"><\/div>",
    name: "Variations in Moves",
    jsStr: "var pgn = '1. e4 e5 ( 1... c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 a6 ( 5... e5 6. Ndb5 a6 7. Na3 b5 8. Nd5 Nxe4 { This is a wild variation } ) 6. Be3 e6 ) 2. Nf3 ( 2. f4 exf4 3. Nf3 g5 ( 3... Nf6 4. e5 Nh5 ) ( 3... Be7 4. Bc4 Bh4+ 5. Kf1 ) 4. h4 ) Nc6 3. Bb5 a6 4. Ba4'\npgnView('b1', {pgn: pgn});",
    jsFn: function() {
        var pgn = '1. e4 e5 ( 1... c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 a6 ( 5... e5 6. Ndb5 a6 7. Na3 b5 8. Nd5 Nxe4 { This is a wild variation } ) 6. Be3 e6 ) 2. Nf3 ( 2. f4 exf4 3. Nf3 g5 ( 3... Nf6 4. e5 Nh5 ) ( 3... Be7 4. Bc4 Bh4+ 5. Kf1 ) 4. h4 ) Nc6 3. Bb5 a6 4. Ba4'
        pgnView('b1', {pgn: pgn});
    }
};
examples["1150"] = {
    desc: "Here is an example game in the style of chess.com",
    html: '<div id="board2" style="width: 300px;margin-right: 25px"></div>',
    name: "Themes: Chess.com",
    jsStr: "var pgn = \"1. e4 e5 2. Nf3 Nc6  ...  24. Bxe7# 1:0\"\;\npgnv = pgnView(\"board2\", {pgn: pgn, position: \"start\", pieceStyle: 'chesscom', theme: 'zeit'});",
    jsFn: function() {
        var pgn = "1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5 4.b4 Bxb4 5.c3 Ba5 6.d4 exd4 7.O-O d3 8.Qb3 Qf6 9.e5 Qg6 10.Re1 Nge7 11.Ba3 b5 12.Qxb5 Rb8 13.Qa4 Bb6 14.Nbd2 Bb7 15.Ne4 Qf5 16.Bxd3 Qh5 { now the whole idea unfolds } 17.Nf6+ gxf6 18.exf6 Rg8 19.Rad1 Qxf3 20.Rxe7+ Nxe7 21.Qxd7+ Kxd7 22.Bf5+ Ke8 23.Bd7+ Kf8 24. Bxe7# 1:0";
        pgnv = pgnView("board2", {pgn: pgn, position: "start", pieceStyle: 'chesscom', theme: 'zeit'});
    }
};
examples["1151"] = {
    desc: "Here the style green for the start position.",
    html: '<div id="board" style="width: 400px; margin-right: 25px">',
    name: "Themes: Green",
    jsStr: "var cfg = { showNotation: false, theme: 'green' };\nvar board = pgnBoard('board', cfg);",
    jsFn: function() {
        var cfg = { showNotation: false, position: 'start', theme: 'green' };
        var board = pgnBoard('board', cfg);
    }
};
examples["1152"] = {
    desc: "",
    html: '<div id="board2" style="width: 400px"></div>',
    name: "Themes: Zeit",
    jsStr: "cfg = { pieceStyle: 'uscf', orientation: 'black', position: 'start', theme: 'zeit'};\nvar board2 = pgnBoard('board2', cfg);",
    jsFn: function() {
        cfg = { pieceStyle: 'uscf', orientation: 'black', position: 'start', theme: 'zeit'};
        var board2 = pgnBoard("board2", cfg);    }
};
examples["1153"] = {
    desc: "Chess board in the informator style",
    html: '<div id="board" style="width: 400px">',
    name: "Themes: Informator",
    jsStr: "var cfg = { showNotation: false, position: 'start', theme: 'informator' };\nvar board = pgnBoard('board', cfg);",
    jsFn: function() {
        var cfg = { showNotation: false, position: 'start', theme: 'informator' };
        var board = pgnBoard('board', cfg);
    }
};
examples["1200"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/2'>ticket 2</a> at GitHub. The idea here is," +
    " that you may define a start position, but don't show the moves (immediately) to allow the reader to" +
    " guess the move",
    html: "",
    name: "#2: Guess the move (unsolved)",
    jsStr: "",
    jsFn: function() {

    }
};
examples["1201"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/3'>ticket 3</a> at GitHub. Add a style " +
    "that looks like the (dark) one at lichess.org. lichess itself has a lot of possibilities, but just mimic " +
    "some of them, especially the ones that have the moves to the right.",
    html: "",
    name: "#3: Add lichess.org (unsolved)",
    jsStr: "",
    jsFn: function() {

    }
};
examples["1202"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/4'>ticket 4</a> at GitHub. Formerly, all " +
    "themes used real buttons for the buttons, but the play buttons are now mostly done with FontAwesome. See the three " +
    "games, the first two with real buttons, the third with font buttons from FontAwesome.",
    html: '<div id="board1" style="width: 400px"></div><div id="board2" style="width: 400px"></div><div id="board3" style="width: 400px"></div>',
    name: "#4: Use FontAwesome for the UI",
    jsStr: "pgnView('board1', { pgn: '1. e4 e5 2. Nf3 Nc6', theme: 'green' });\npgnView('board2', { pgn: '1. e4 e5 2. Nf3 Nc6', theme: 'blue' });\npgnView('board3', { pgn: '1. e4 e5 2. Nf3 Nc6' });",
    jsFn: function() {
        pgnView('board1', { pgn: '1. e4 e5 2. Nf3 Nc6', theme: 'green' });
        pgnView('board2', { pgn: '1. e4 e5 2. Nf3 Nc6', theme: 'blue' });
        pgnView('board3', { pgn: '1. e4 e5 2. Nf3 Nc6' });
    }
};
examples["1203"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/5'>ticket 5</a> at GitHub. Shows in an example " +
    "that the input with captures leads to output that include in the capture moves the character 'x'",
    html: '<div id="board1" style="width: 400px"/>',
    name: "#5: Missing capture symbol",
    jsStr: "pgnView('board1', { pgn: '1. e4 e5 2. Nf3 Nc6 3. d4 exd4 4. Nxd4 Nf6 5. Nc3 Nxd4 6. Qxd4' });",
    jsFn: function() {
        pgnView('board1', { pgn: '1. e4 e5 2. Nf3 Nc6 3. d4 exd4 4. Nxd4 Nf6 5. Nc3 Nxd4 6. Qxd4' });
    }
};
examples["1204"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/6'>ticket 6</a> at GitHub. " +
    "The boards above have the three locales fr, de, and en, and show the moves initially in the language " +
    "of choice. However, when you edit the games, you will see that the last locale (here english) is used " +
    "in all of them.",
    html: '<div id="board" style="width: 200px;float: left;margin-right: 20px"></div>\n<div id="board1" style="width: 200px;float: left;margin-right: 20px"></div>\n<div id="board2" style="width: 200px;float: left;margin-right: 20px"></div>',
    name: "#6: locale in edit mode",
    jsStr: "var pgn = '1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5';\npgnEdit('board', {pgn: pgn, locale: 'fr'});\npgnEdit('board1', {pgn: pgn,locale: 'de'});\npgnEdit('board2', {pgn: pgn, locale: 'en'});",
    jsFn: function() {
        var pgn = "1. e4 e5 2. Nf3 Nc6  3.Bc4 Bc5";
        pgnEdit("board", {pgn: pgn, locale: 'fr'});
        pgnEdit("board1", {pgn: pgn,locale: 'de'});
        pgnEdit("board2", {pgn: pgn, locale: 'en'});
    }
};
examples["1205"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/9'>ticket 9</a> at GitHub. " +
    "The example shows different nags ('$' followed by a number) with variations in white space " +
    "directly before it. ",
    html: '<div id="board" style="width: 300px"/>',
    name: "#9: spaces after a half move before a NAG",
    jsStr: 'pgnView("board", {pgn: "1. e4 $1 e5 $2 2. Nf3 $3 Nc6 $4 3. Bc4$13 Bc5$14 4. c3$15 Nf6$16"});',
    jsFn: function() {
        pgnView("board", {pgn: "1. e4 $1 e5 $2 2. Nf3 $3 Nc6 $4 3. Bc4$13 Bc5$14 4. c3$15 Nf6$16"});
    }
};
examples["1206"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/10'>ticket 10</a> at GitHub. Demonstrates " +
    "that additional move numbers from black are allowed where it makes sense. With a longer comment, the move " +
    "number may help in the orientation of the reader (when constructing the PGN string).",
    html: '<div id="board" style="width: 300px"/>',
    name: "#10: repeating move number",
    jsStr: 'pgnView("board", {pgn: "1. e4 { comment } 1... e5"});',
    jsFn: function() {
        pgnView("board", {pgn: "1. e4 { comment } 1... e5"});
    }
};
examples["1207"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/11'>ticket 11</a> at GitHub. " +
    "As you can see, black has with move 4 two possibilities to capture back the bishop, and the chosen one " +
    "was clearly included in the pgn provided, but was not displayed in the output of PGN.",
    html: "<div id='board' style='width: 360px'/>",
    name: "#11: disabmbiguation in print format",
    jsStr: 'pgnView("board", {pgn: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Bxc6 dxc6"});',
    jsFn: function() {
        pgnView("board", {pgn: "1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Bxc6 dxc6"});
    }
};
examples["1208"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/12'>ticket 12</a> at GitHub. The idea " +
    "here is, that more than one pgn game could be included for the same viewer, and the viewer would then " +
    "allow to first select the game, and then play through the game.",
    html: "",
    name: "#12: display of many games (unsolved)",
    jsStr: "",
    jsFn: function() {

    }
};
examples["1209"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/13'>ticket 13</a> at GitHub. " +
    "The problem here was, that when a game in edit mode was provided with a start position with black " +
    "to move, this was not recognized by the viewer. Hover over the black pieces to see that they are " +
    "the only ones now to move.",
    html: "<div id='board' style='width: 360px'/>",
    name: "#13: FEN not recognized",
    jsStr: 'pgnEdit("board", {position: "rnbqkbnr/pp1p1ppp/4p3/4P3/2PQ4/2N5/PP3PPP/R1B1KBNR b KQkq - 0 6"});',
    jsFn: function() {
        pgnEdit("board", {position: "rnbqkbnr/pp1p1ppp/4p3/4P3/2PQ4/2N5/PP3PPP/R1B1KBNR b KQkq - 0 6"});

    }
};
examples["1210"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/14'>ticket 14</a> at GitHub. " +
    "Currently, the result of a game (as part of the notation, not the header) is parsed, but not " +
    "displayed as part of the notation.",
    html: "<div id='board' style='width: 360px'/>",
    name: "#14: Parsing rules for result",
    jsStr: 'pgnView("board", {pgn: "1. f4 e6 2. g4 Qh4# 0:1"});',
    jsFn: function() {
        pgnView("board", {pgn: "1. f4 e6 2. g4 Qh4# 0:1"});
    }
};
examples["1211"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/16'>ticket 16</a> at GitHub. " +
    "The parser is not as robust as it could be so I have to add some flexibility here. The " +
    "following is only one of many examples that the rules for reading are more strict that they should be.",
    html: "<div id='board' style='width: 360px'/>",
    name: "#16: Make import more robust",
    jsStr: 'pgnView("board", {pgn: "1. f4 e6 2. g4 Qd8-h4#"});',
    jsFn: function() {
        pgnView("board", {pgn: "1. f4 e6 2. g4 Qd8-h4#"});
    }
};
examples["1212"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/19'>ticket 19</a> at GitHub. " +
    "This could be a feature to provide additional functions to allow adding moves. " +
    "This is currently implemented (only) to allow adding moves at the end to the current position, " +
    "I don't know what will happen if you do that at any other place. Please have a look into the " +
    "real example in `examples/pgnAddMoves.html`. The following is not the real example ...",
    html: "<div id='board' style='width: 360px'/>",
    name: "#19: Adding moves from a backend in real time",
    jsStr: 'pgnView("board", {pgn: "1. f4 e6 2. g4 Qh4# 0:1"});',
    jsFn: function() {
        pgnView("board", {pgn: "1. f4 e6 2. g4 Qh4# 0:1"});
    }
};
examples["1213"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/20'>ticket 20</a> at GitHub. " +
    "Clicking on variations in Firefox didn't worked at all.",
    html: "<div id='b1' style='width: 360px'/>",
    name: "#20: Clicking on variation in Firefox does not work",
    jsStr: 'var pgn = \'1. e4 e5 ( 1... c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 a6 ( 5... e5 6. Ndb5 a6 7. Na3 b5 8. Nd5 Nxe4 { This is a wild variation } ) 6. Be3 e6 ) 2. Nf3 ( 2. f4 exf4 3. Nf3 g5 ( 3... Nf6 4. e5 Nh5 ) ( 3... Be7 4. Bc4 Bh4+ 5. Kf1 ) 4. h4 ) Nc6 3. Bb5 a6 4. Ba4\';\npgnView(\'b1\', {pgn: pgn});',
    jsFn: function() {
        var pgn = '1. e4 e5 ( 1... c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 a6 ( 5... e5 6. Ndb5 a6 7. Na3 b5 8. Nd5 Nxe4 { This is a wild variation } ) 6. Be3 e6 ) 2. Nf3 ( 2. f4 exf4 3. Nf3 g5 ( 3... Nf6 4. e5 Nh5 ) ( 3... Be7 4. Bc4 Bh4+ 5. Kf1 ) 4. h4 ) Nc6 3. Bb5 a6 4. Ba4'
        pgnView('b1', {pgn: pgn});    }
};
examples["1214"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/21'>ticket 21</a> at GitHub. " +
    "The results 1-0 and 0-1 in the move notation led to a failure at the end.",
    html: "<div id='board' style='width: 360px'/>",
    name: "#21: Parsing rules for result",
    jsStr: 'pgnView("board", {pgn: "1. f4 e6 2. g4 Qh4# 0-1"});',
    jsFn: function() {
        pgnView("board", {pgn: "1. f4 e6 2. g4 Qh4# 0-1"});
    }
};
examples["1215"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/22'>ticket 22</a> at GitHub. " +
    "Integrate stockfish.js in the viewer, to allow analyzing games ad hoc.",
    html: "<div id='board' style='width: 360px'/>",
    name: "#22: Integrate stockfish.js in the viewer (unsolved)",
    jsStr: 'pgnView("board", {pgn: "1. f4 e6 2. g4 Qh4# 0:1"});',
    jsFn: function() {
        pgnView("board", {pgn: "1. f4 e6 2. g4 Qh4# 0:1"});
    }
};
examples["1216"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/23'>ticket 23</a> at GitHub. " +
    "Use the pgn notation flag 'setup' and interpret it the right way as replacement for the fen parameter.",
    html: "<div id='board' style='width: 360px'/>",
    name: "#23: Use the pgn notation flag 'setup'",
    jsStr: "pgnView('board', {pgn: '[SetUp \"1\"][FEN \"rnbqkbnr/1ppppppp/p7/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2\"] 2. Nc3 e5 3. Nf3 Qe7'});",
    jsFn: function() {
        pgnView("board", {pgn: "[SetUp \"1\"]\
        [FEN \"rnbqkbnr/1ppppppp/p7/8/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2\"] 2. Nc3 e5 3. Nf3 Qe7"});
    }
};
examples["1217"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/25'>ticket 25</a> at GitHub. " +
    "Separate the generated DIVs, allow additional markup. The order here is board, moves, then buttons" +
    "not as usual board, buttons and then the moves",
    html: "<div id='board' style='width: 200px'></div><div id='moves'></div><div id='button'></div>",
    name: "#25: Allow different markup",
    jsStr: 'pgnView({inner: "board", moves: "moves", button: "button"}, {pgn: "1. f4 e6 2. g4 Qh4#"})',
    jsFn: function() {
        pgnView({inner: "board", moves: "moves", button: "button"}, {pgn: "1. f4 e6 2. g4 Qh4#"});
    }
};
examples["1218"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/26'>ticket 26</a> at GitHub. " +
    "Viewer does not symbolize check (+) or mate (#).",
    html: "<div id='board' style='width: 200px'/>",
    name: "#26: Symbolize check or mate",
    jsStr: 'pgnView("board", {pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"})',
    jsFn: function() {
        pgnView("board", {pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"});
    }
};
examples["1219"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/27'>ticket 27</a> at GitHub. " +
    "Viewer should be robust if check and mate symbols are not included.",
    html: "<div id='board' style='width: 200px'/>",
    name: "#27: Be robust if check or mate are not included",
    jsStr: 'pgnView("board", {pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"})',
    jsFn: function() {
        pgnView("board", {pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"});
    }
};
examples["1220"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/28'>ticket 28</a> at GitHub. " +
    "Should accept Long Algebraic Notation in various forms.",
    html: "<div id='board' style='width: 200px'/>",
    name: "#28: Should accept Long Algebraic Notation in various forms",
    jsStr: 'pgnView("board", {pgn: "1. e2-e4 e7-e5 2. Ng1-f3 d6 3. d4 e5xd4"})',
    jsFn: function() {
        pgnView("board", {pgn: "1. e2-e4 e7-e5 2. Ng1-f3 d6 3. d4 e5xd4"});
    }
};
examples["1221"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/30'>ticket 30</a> at GitHub. " +
    "Underpromotion in edit mode possible.",
    html: "<div id='board' style='width: 200px'/>",
    name: "#30: Underpromotion in edit mode possible (unsolved)",
    jsStr: 'pgnView("board", {pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5#43 Bxd1 6. Bxf7 Ke7 7. Nd5"})',
    jsFn: function() {
        pgnView("board", {pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"});
    }
};
examples["1222"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/31'>ticket 31</a> at GitHub. " +
    "Show meaningful error message when PGN is wrong.",
    html: "<div id='board' style='width: 200px'/>",
    name: "#31: Show meaningful error message when PGN is wrong",
    jsStr: 'pgnView("board", {pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd4"})',
    jsFn: function() {
        pgnView("board", {pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd4"});
    }
};
examples["1223"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/32'>ticket 32</a> at GitHub. " +
    "Internationalization of buttons does not work as expected. Hover over the buttons to see the result.",
    html: "Locale fr <div id='board' style='width: 200px'></div> Locale nl <div id='board2' style='width: 200px'></div> Locale cs <div id='board3' style='width: 200px'></div>",
    name: "#32: Internationalization of buttons",
    jsStr: 'pgnEdit("board", {locale: "fr", pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"})\npgnEdit("board2", {locale: "nl", pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"});\npgnEdit("board3", {locale: "cs", pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"});',
    jsFn: function() {
        pgnEdit("board", {locale: "fr", pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"});
        pgnEdit("board2", {locale: "nl", pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"});
        pgnEdit("board3", {locale: "cs", pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"});
    }
}; 
examples["1224"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/33'>ticket 33</a> at GitHub. " +
    "buttons:first should go to the start position. Jump to the ennd and back to beginning. Make some moves, and jump back to the beginning to see that.",
    html: "<div id='board' style='width: 200px'/>",
    name: "#33: buttons:first should go to the start position",
    jsStr: 'pgnView("board", {pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"})',
    jsFn: function() {
        pgnView("board", {pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"});
    }
};
examples["1225"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/36'>ticket 36</a> at GitHub. " +
    "Add a UI for FEN and PGN in edit mode (PGN already there, FEN missing) and view mode (should then be per default off, here switched on).",
    html: "<div id='board' style='width: 200px'></div><div id='board1' style='width: 200px'></div>",
    name: "#36: Add UI for FEN and PGN in edit mode",
    jsStr: 'pgnView("board", {showFen: true, pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"});\npgnEdit("board1", {pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"})',
    jsFn: function() {
        pgnView("board", {showFen: true, pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"});
        pgnEdit("board1", {pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"})
    }
};
examples["1226"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/37'>ticket 37</a> at GitHub. " +
    "Add additional languages: take some locales : cs, da, de, en, es, et, fi ,fr, hu, is, it nb, nl, pl, pt, ro, sv.",
    html: "<div>Default language: en, Locale es and Locale fi</div>\n<div id='board1' style='width: 200px; float: left'></div>\n<div id='board2' style='width: 200px; float: left'></div>\n<div id='board3' style='width: 200px; float: left'></div>",
    name: "#37: Add additional languages",
    jsStr: 'pgn = "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6";\npgnEdit("board1", {pgn: pgn});\npgnEdit("board2", {pgn: pgn, locale: "es"});\npgnÊdit("board3", {pgn: pgn, locale: "fi"});',
    jsFn: function() {
        pgn = "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6";
        pgnEdit("board1", {pgn: pgn});
        pgnEdit("board2", {pgn: pgn, locale: "es"});
        pgnEdit("board3", {pgn: pgn, locale: "fi"});
    }
};
examples["1227"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/39'>ticket 39</a> at GitHub. " +
    "Allow opening of examples from the documentation in a separate tab. Just click on the link 'View example in new window'.",
    html: "<div id='board' style='width: 350px'/>",
    name: "#39: Allow opening of examples from the documentation in a separate tab",
    jsStr: 'pgnView("board", {pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"})',
    jsFn: function() {
        pgnView("board", {pgn: "1. e4 e5 2. Nf3 d6 3. Bc4 Bg4 4. Nc3 h6 5. Nxe5 Bxd1 6. Bxf7 Ke7 7. Nd5"});
    }
};
examples["1228"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/42'>ticket 42</a> at GitHub. " +
    "Allow using PGN from an external source.",
    html: "<div id='board' style='width: 350px'/>",
    name: "#42: Allow using PGN from an external source",
    jsStr: 'pgnView("board", {pgnFile: "/docu/example/cori-vishnu.pgn"})',
    jsFn: function() {
        pgnView("board", {pgnFile: "/docu/example/cori-vishnu.pgn"});
    }
};
examples["1229"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/43'>ticket 43</a> at GitHub. " +
    "Ugly display of tags.",
    html: "<div id='board' style='width: 200px'/>",
    name: "#43: Ugly display of tags (unsolved)",
    jsStr: 'pgnView("board", {pgnFile: "/docu/example/cori-vishnu.pgn"})',
    jsFn: function() {
        pgnView("board", {pgnFile: "/docu/example/cori-vishnu.pgn"});
    }
};
examples["1230"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/44'>ticket 44</a> at GitHub. " +
    "Add the NAGs from a move to the NAG menu. Edit the game, and add NAGs to a move which has already NAGs",
    html: "<div id='board' style='width: 200px'/>",
    name: "#44: Add the NAGs from a move to the NAG menu",
    jsStr: 'pgnEdit("board", {pgn: "1. e4 e5 2. Nf3! d6? 3. Bc4?! Bg4 4. Nc3 h6 5. Nxe5 Bxd1?? 6. Bxf7 Ke7 7. Nd5"})',
    jsFn: function() {
        pgnEdit("board", {pgn: "1. e4 e5 2. Nf3! d6? 3. Bc4?! Bg4 4. Nc3 h6 5. Nxe5 Bxd1?? 6. Bxf7 Ke7 7. Nd5"});
    }
};
examples["1232"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/46'>ticket 46</a> at GitHub. " +
    "Add the NAGs from a move to the NAG menu. Edit the game, and add NAGs to a move which has already NAGs",
    html: "<div id='board' style='width: 200px'/>",
    name: "#46: Allow FEN string with PGN to define start position from analysis",
    jsStr: 'pgnEdit("board", {pgn: "1. e4 e5 2. Nf3! d6? 3. Bc4?! Bg4 4. Nc3 h6 5. Nxe5 Bxd1?? 6. Bxf7 Ke7 7. Nd5"})',
    jsFn: function() {
        pgnEdit("board", {pgn: "1. e4 e5 2. Nf3! d6? 3. Bc4?! Bg4 4. Nc3 h6 5. Nxe5 Bxd1?? 6. Bxf7 Ke7 7. Nd5"});
    }
};
examples["1233"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/47'>ticket 47</a> at GitHub (unsolved). " +
    "2 cases: start with move 3 from FEN, but shows 1; start with a black move, but move number is wrong.",
    html: "<div id='board1' style='width: 200px'></div><div id='board2' style='width: 200px'></div>",
    name: "#47: Ensure that move numbers are 'correct' (unsolved)",
    jsStr: 'pgnEdit("board1", {pgn: "1. Bc4 Bc5", position: "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3"});\npgnEdit("board2", {pgn: "1... e5", position: "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1"});',
    jsFn: function() {
        pgnEdit("board1", {pgn: "1. Bc4 Bc5", position: "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3"});
        pgnEdit("board2", {pgn: "1... e5", position: "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1"});
    }
};
examples["1234"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/48'>ticket 48</a> at GitHub. " +
    "??",
    html: "<div id='board' style='width: 200px'></div><div id='b1' style='width: 200px'></div>",
    name: "#48: Fix broken green and blue themes",
    jsStr: 'pgnEdit("board", {theme: "green"}); pgnView("b1", {theme: "blue"})',
    jsFn: function() {
        pgnEdit("board", {theme: "green"}); pgnView("b1", {theme: "blue"});
    }
};
examples["1235"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/49'>ticket 49</a> at GitHub. " +
    "Fixed differences in the examples only for PGN and FEN.",
    html: "<div id='board' style='width: 200px'/>",
    name: "#49: Fix example style corresponding color of buttons",
    jsStr: 'pgnView("board", {theme: "green", pgn: "1. e4 e5 2. Nf3! d6? 3. Bc4?! Bg4 4. Nc3 h6 5. Nxe5 Bxd1?? 6. Bxf7 Ke7 7. Nd5"})',
    jsFn: function() {
        pgnEdit("board", {theme: "green", pgn: "1. e4 e5 2. Nf3! d6? 3. Bc4?! Bg4 4. Nc3 h6 5. Nxe5 Bxd1?? 6. Bxf7 Ke7 7. Nd5"});
    }
};

examples["1236"] = {
    desc: "See <a href='https://github.com/mliebelt/PgnViewerJS/issues/50'>ticket 50</a> at GitHub. " +
    "Missing column letter in pawn moves with captures. Play some moves with pawn captures to see it.",
    html: "<div id='board' style='width: 200px'/>",
    name: "#49: Pawn Capture Bug",
    jsStr: 'pgnView("board", {theme: "green"})',
    jsFn: function() {
        pgnEdit("board", {theme: "green"});
    }
};
